### PR TITLE
Add title bar count component

### PR DESCRIPTION
**Pull request by DzoQiEuoi**
This PR adds the title bar count component.

## Changes

-

## Fixes

-

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by topliceanurazvan** [comment]
Is this used inside of the actual `TitleBar` component?

**Comment by DzoQiEuoi** [comment]
> Is this used inside of the actual `TitleBar` component?

It can be used as the action to represent the file count. I'm not sure if we'd use it elsewhere.

**Comment by topliceanurazvan** [comment]
Then should it add it directly inside of the `TitleBar` with some prop instead of creating a whole new component?

**Comment by DzoQiEuoi** [comment]
> Then should it add it directly inside of the `TitleBar` with some prop instead of creating a whole new component?

It could be but then it adds complexity to the TitleBar interface and it's not very flexible in case we ever want a different kind of counter. Maybe we could export it as `TitleBar.Count` then we get the best of both worlds as long as we don't ever want to use it in a different component which seems unlikely.

**Comment by topliceanurazvan** [comment]
Let's just keep it like this then

**Review by topliceanurazvan — APPROVED** [review]

**Pull request merged**
